version: "3.9"
services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/ali-mirror/admin:0.0.1
    restart: always
    ports:
        - "8081:80"
    volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf