version: "3.9"
services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/ali-mirror/admin:0.0.1
    restart: always
    ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"
        - "10003:10003"
    volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf