version: "3.9"
services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/ali-mirror/docs:0.0.2
    restart: always
    ports:
        - "8080:80"
    volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf