version: "3.9"
services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/ali-mirror/docs:0.0.1
    restart: always
    ports:
        - "20000:20000"
        - "20001:20001"
        - "20002:20002"
        - "20003:20003"
        - "20004:20004"
    volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf